FROM oven/bun:1

WORKDIR /usr/src/app

ARG DATABASE_URL

COPY ./packages ./packages
COPY ./bun.lock ./bun.lock

COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json

COPY ./apps/web ./apps/web

COPY . .


RUN bun install
RUN bun run db:generate
RUN DB_URL=$DB_URL bunx turbo build --filter=web...

EXPOSE 3000

CMD ["bun","run" ,"start:web"]
